# Generated by Django 4.2.23 on 2025-10-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('niño', 'Niño'), ('joven', 'Joven'), ('servidor', 'Servidor')], max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ultima_asistencia', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.CharField(blank=True, choices=[('Maestro', 'Maestro'), ('Lider', 'Líder')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=255)),
                ('maestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_dirigidas', to='asistencia.integrante')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.integrante')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.reunion')),
            ],
            options={
                'unique_together': {('integrante', 'reunion')},
            },
        ),
    ]
