# Generated by Django 4.2.23 on 2025-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='tipo',
            field=models.CharField(choices=[('J', 'Jovenes'), ('N', 'Niños y preadolescentes')], default='J', max_length=1),
        ),
    ]
