# Generated by Django 4.2.23 on 2025-10-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_reunion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asistio',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
    ]
