# Generated by Django 4.2.23 on 2026-01-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_asistencia_asistio_asistencia_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
