# Generated by Django 4.2.23 on 2026-01-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_integrante_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
