# Generated by Django 4.2.23 on 2026-01-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_integrante_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='integrantes/'),
        ),
    ]
