# Generated by Django 4.2.23 on 2026-01-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_integrante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
