# Generated by Django 4.2.23 on 2026-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_integrante_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=models.ImageField(blank=True, default='integrantes/user_default.png', null=True, upload_to='integrantes/'),
        ),
    ]
