# Generated by Django 4.2.23 on 2026-01-14 06:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_integrante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
